### ISSUE TITLE
Create New Member not working in v3

### ISSUE THREAD

**Issue by sabernar** [amro/gibbon#121]
Gibbon (v3 branch) is working for me for viewing lists:

          mailchimp_list = gibbon.lists("8459999c08").members.retrieve

but not for creating a new member of the list:

          gibbon.lists("8459999c08").members.create(body: {email_address: "email_address", status: "subscribed", merge_fields: {FNAME: "First Name", LNAME: "Last Name"}})

It is giving me a 400 error:

         Gibbon::MailChimpError (the server responded with status 400):
         app/controllers/orders_controller.rb:152:in `payment'

Any ideas?

**Comment by amro** [comment]
Hmm, that looks correct. Is there any more detail to the error? I'll take a look tonight.

**Comment by amro** [comment]
Okay, I gave it a shot and it worked fine for me:

    g.lists(my_list_id).members.create(body: {email_address: "myemail+222@gmail.com", status: "subscribed", merge_fields: {FNAME: "First Name", LNAME: "Last Name"}})

One note is if the email is already registered, the API will return an error. In that case you need to call `update` instead of `create`. To troubleshoot this in the future, rescue Gibbon::MailChimpError when you make a call. Then examine it's `title`, `detail`, and `body` attributes. You'll see what the API is returning.

I'm guessing the email is already registered.

**Comment by amro** [comment]
Example output:

    {"type"=>"http://kb.mailchimp.com/api/error-docs/400-invalid-resource", "title"=>"Invalid Resource", "status"=>400, "detail"=>"the_email_i_tried@gmail.com is already a list member.  Use PATCH to update existing members.", "instance"=>"f806a7ca-00bc-4e67-901c-e02acdbb6eae"}

**Comment by rfunduk** [comment]
For anyone who comes along later, I also ran into this. The error JSON was:

```json
{
  "type": "http://kb.mailchimp.com/api/error-docs/400-invalid-resource",
  "title": "Invalid Resource",
  "status": 400,
  "detail": " is already a list member.  Use PATCH to update existing members.",
  "instance": "<UUID HERE>"
}
```

Notice how there is no email address listed. `<blank> is already a list member.`

I dug into it it turned out that MailChimp doesn't like `@example.com` addresses and gives this error if you try to use one. I suppose that makes sense... but I would prefer "blah@example.com is not a valid email address." or similar :)
