### ISSUE TITLE
Creating a subscription, adding people to GROUPS

### ISSUE THREAD

**Issue by CanvasCut** [amro/gibbon#130]
I've been through a lot of different ideas on how to get this together.  I've tried using the merge vars, I have tried lists(id).interests, etc.  Could someone throw me a quick little example of adding a subscriber to a group?  Thanks a lot

**Comment by amro** [comment]
Using API v3 can be a little confusing. Let me go through how I figured it out. The documentation is manually in JSON schemas. Here's the schema for a [list member](https://us9.api.mailchimp.com/schema/3.0/Lists/Members/Instance.json). Note the "interests" dictionary.

At this point, I wanted to see what existing data looked like so I fetched a member from an existing list:

    g.lists(list_id).members(member_id).retrieve

The relevant bit of the response looked like this:

    {"id"=>"...", "email_address"=>"...", ..., "interests"=>{"3def637141"=>true, "f7cc4ee841"=>false, "fcdc951b9f"=>false, "3daf3cf27d"=>true, "293a3703ed"=>false, "72370e0d1f"=>false, "d434d21a1c"=>false, "bdb1ff199f"=>false, "a54e78f203"=>false, "c4527fd018"=>false}

So it's a map of interest ID to boolean value. So how do we get interest details so we can get the interest ID? Well, looking at [this doc page](http://kb.mailchimp.com/api/resources/lists/interest-categories/interests/lists-interests-collection), we need to do this:

    g.lists(list_id).interest_categories.retrieve

To get a list of interest categories. That gives us something like:

    {"list_id"=>"...", "categories"=>[{"list_id"=>"...", "id"=>"0ace7aa498", "title"=>"Food Preferences", ...}] ...}

The ID we're interested in is "0ace7aa498," which will let us fetch a list of details for this interest group:

    g.lists(list_id).interest_categories("0ace7aa498").interests.retrieve

That response gives the interest data, including the ID for the interests themselves. Now we can update like this:

    g.lists("31067f2f53").members("912ba5a26c1634b9b3d446546c529773").update(body: {interests: {"3def637141": true, "f7cc4ee841": false}})

Hope that helps.

**Comment by CanvasCut** [comment]
Is there a way to do all of this when creating the initial subscription?  If not, I've been having trouble going from Mailchimp's API documentation to creating something usable through Gibbon.  

https://apidocs.mailchimp.com/api/2.0/lists/member-info.php
To implement member-info, I was trying things like: 
g.member_info("LIST-ID", [{email: "USER-EMAIL"}]).retrieve

My understanding is off, I'm aware.  Is there a general rule of thumb?

Thanks a lot for your help.

**Comment by amro** [comment]
Okay - two things up front. MailChimp has versioned their API. If you want to use API v2, you need to use an old version of Gibbon (v1.2.1). That works very differently from API v2, which the current version of Gibbon works with. I'd suggest hitting the new version of the API since that's what MailChimp recommends.

When you say "is there a way to do all of this when creating the initial subscription?" do you mean is there a way to set interests when subscribing a user without making a second call to update? Yes, I'm sure when you subscribe a user you can just pass the list of interests as I have above as part of the `body` parameter. The key here is knowing the list ID, and the IDs of the interests you want to assign to the user. If you know those things up front, then it's a matter of making a simple call. An example of this that sets merge fields and interests might look like:

    g.lists(list_id).members.create(body: {email_address: user_email_address, status: "subscribed", merge_fields: {FNAME: "Bob", LNAME: "Smith"}, interests: {some_interest_id: true, another_interest_id: true}})
