### ISSUE TITLE
Obtaining an interest ID from interest title

### ISSUE THREAD

**Issue by DanielKehoe** [amro/gibbon#135]
The README provides an example of obtaining a list of interest categories for any mailing list:
```
gibbon.lists(list_id).interest_categories.retrieve
```
This returns a hash of categories with IDs and titles.

Can you expand the example to show the Ruby code that we should use to get the category ID if we only know the category title?

Or even better, would you consider adding a Gibbon API method to look up a category ID given parameters of list ID and category title? Like:
```
g.lists(list_id).interest_categories.retrieve_id_by_title('some_category_title')
```

**Comment by amro** [comment]
Gibbon is built to map onto MailChimp's API 1-to-1. It doesn't actually declare any concrete or helper methods. Instead, it uses method_missing (i.e. meta programming) to take your syntax and turn it into a URL and parameters to pass to the API directly. Adding a helper, as you've suggested, is outside of what I want to offer because it doesn't fit into that pattern.

I looked at MailChimp's API docs for an [Interest Category instance](https://us9.api.mailchimp.com/schema/3.0/Lists/InterestCategories/Instance.json) and it does not allow one to fetch by title - just ID (so far as I can see). If they add that functionality then Gibbon will support it without a need for an update. Otherwise, you simply need to do is something like:

    def interest_category_by_title(categories, title)
        return nil if (categories.nil? || title.nil?)
        
        categories.each do |category|
            if category["title"] == title
               return category
            end
        end
        
        return nil
    end

I didn't try the code above but it should be close to what you need.

**Comment by DanielKehoe** [comment]
Thanks!

**Comment by DanielKehoe** [comment]
The actual implementation is much more complex. Though perhaps I've overlooked a way to simplify it?

I've got a User object with an attribute ```affinity``` and my MailChimp list has a Group (a Category) named "AFFINITY." Here's what I do to subscribe a member and set an interest:

```
  def subscribe(user)
    mailchimp = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)
    list_id = Rails.application.secrets.mailchimp_list_id
    unless user.affinity.blank?
      category_title = 'AFFINITY'
      interest_name = user.affinity
      interest_id = interest_id_by_name(mailchimp, list_id, category_title, interest_name)
      result = mailchimp.lists(list_id).members.create(
        body: {
          email_address: user.email,
          status: 'subscribed',
          interests: {interest_id => true}
      })
    else
      result = mailchimp.lists(list_id).members.create(
        body: {
          email_address: user.email,
          status: 'subscribed'
      })
    end
    Rails.logger.info("Subscribed #{user.email} to MailChimp") if result
  end

  def interest_id_by_name(mailchimp, list_id, category_title, interest_name)
      return nil if (list_id.nil? || category_title.nil? || interest_name.nil?)
      category_id = category_id_by_title(mailchimp, list_id, category_title)
      interests = mailchimp.lists(list_id).interest_categories(category_id).interests.retrieve
      interests['interests'].each do |interest|
        if interest['name'] == interest_name
          return interest['id']
        end
      end
      return nil
  end

  def category_id_by_title(mailchimp, list_id, category_title)
      return nil if (list_id.nil? || category_title.nil?)
      json_hash = mailchimp.lists(list_id).interest_categories.retrieve
      json_hash['categories'].each do |category|
        if category['title'] == category_title
          return category['id']
        end
      end
      return nil
  end
```
It's pretty gnarly.
