### ISSUE TITLE
Retrieve list of members in a group (/interest)

### ISSUE THREAD

**Issue by netpenthe** [amro/gibbon#142]
I can successfully retrieve a group like this;

`gb.lists("aaa").interest_categories("xxx").interests("yyy").retrieve`

But I would now like to get a list of members from this group.

Ideally I could just retrieve the member id's and the email addressese.

I thought I could do this:

`gb.lists("aaa").interest_categories("xxx").interests("yyy").members.retrieve`

but no luck :(

Any help would be appreciated.

**Comment by amro** [comment]
Hi @netpenthe. I don't believe you can do this directly but I suggest contacting MailChimp support to double check that.

What I believe you should do is create a list segment then fetch the members in that segment. MailChimp has [APIs](http://kb.mailchimp.com/api/resources) for that but I have not gone through the exercise with Gibbon 2. The gist (no pun intended) is you would POST to `lists/segments/collection.json` and GET the `lists/segments/instance.json`.

So you know, Gibbon maps onto MailChimp's API 1-to-1. What you type in terms of syntax is turned into a URL to hit and the HTTP verb used depends on the verb you tack onto the end of your statement.

So my recommendation here is to consult MailChimp's API docs and email their support for folks to figure out how you would create the segment via HTTP calls, then map them onto Gibbon. MailChimp's [API playground](https://us1.api.mailchimp.com/playground/) could be helpful while figuring it out.

**Comment by netpenthe** [comment]
Hi @amro 
Thanks for the reply.

I created the segments manually using the webpage and am able to get the details of my segment like:

`gb.lists(list_id).segments(segment_id).retrieve`

However I can't see anyway to download the actual list of members.

I took a look at the API Playground but it doesn't seem to support segments in the "List" filtering section... :/

**Comment by amro** [comment]
@netpenthe, I just spent a few minutes and I can't figure it out either. It may be possible with their new batches API, or it might simply be a case of needing to filter properly when GET-ting members of a list. If you look at the playground page for list members, you'll see you can filter by some fields (such as email_type). But you can't filter by interests, even though that's a property in the schema. That's probably because that would be tough to do as a query param. I'm wondering if there's some particular syntax they expect to receive to let one filter by segment or by interest group.

Can you try contact MailChimp support to see if they can point you in the right direction? I'd love to see their response and would be glad to help you figure out how to make the request using Gibbon afterward.

**Comment by amro** [comment]
Following up: Did you hear back from MailChimp?

**Comment by amro** [comment]
Closing for now. Let me know if there's something Gibbon related I can help with.
