### ISSUE TITLE
Support batch requests

### ISSUE THREAD

**Issue by jgadbois** [amro/gibbon#149]
Can you add support for batch requests? - http://kb.mailchimp.com/api/article/how-to-use-batch-operations

**Comment by amro** [comment]
I shouldn't need to do anything specific to Gibbon to support this. You just need to map the API calls from the guide to Ruby syntax. e.g. to get a specific batch, you would do something like:

    gibbon.batches(batch_id).retrieve

**Comment by jgadbois** [comment]
I was thinking more of a way to easily build a batch to POST (to bulk update subscribers or something)

**Comment by amro** [comment]
I see. Thanks for the suggestion. A major (and primary) goal of Gibbon is to map as closely to the API as possible so one can look at MailChimp's API docs and use Gibbon without having to learn special usage syntax for the library. Adding some custom syntax for batches would go against that and make it so folks would need to look more at Gibbon's documentation than MailChimp's.

**Comment by jgadbois** [comment]
Ok, so for batch requests, just manually build the batch requests in a nested hash I guess?

https://us9.api.mailchimp.com/schema/3.0/Batches/Create.json?_ga=1.218532761.1464569017.1438332259

**Comment by amro** [comment]
Yep, build the nested hash as needed. I would approach it by writing a method to create the hash for a single user, and another to aggregate those user hashes to create the parameters as the API expects.

**Comment by amro** [comment]
I'm closing this, but please let me know if you run into some other issue with Gibbon.

**Comment by jgadbois** [comment]
Thanks, I'm going to try to avoid bulk wherever possible for now

**Comment by SirRawlins** [comment]
Hey gang, I've just upgraded devise_campaignable to the latest Gibbon and it uses the batch process for bulk subscription/unsubscription. As suggested you just have to manually compile an array of operations to perform and send those through Gibbon to the batch endpoint.

https://github.com/sorry-app/devise_campaignable/blob/master/lib/devise_campaignable/adapters/mailchimp.rb#L40

I'm sure we could wrap this concept up in some helper methods which would help with queuing traditional Gibbon requests, rather than having to build your own operations hashes and arrays.

Maybe some food for thought.
