### ISSUE TITLE
Support for sending a campaign

### ISSUE THREAD

**Issue by q3-tech** [amro/gibbon#159]
I'm trying to send an existing campaign using the [this](http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/#action-post_campaigns_campaign_id_actions_send) API end point. 
Gibbon doesnt seem to support it yet? Or am I missing something?

**Comment by amro** [comment]
Hi Nitin, Can you give me a little more detail, please? Can I see the line where you try to make the call and the error you receive?

**Comment by q3-tech** [comment]
I thought something like this work - 
`gb.campaigns(campaign_id).actions.send`
would work. 
But I looked through the code "actions.send" isn't supported yet.
Are you planning to include that sometime soon?

**Comment by amro** [comment]
Nitin, I understand why you're confused now. Gibbon maps onto MailChimp's API 1-to-1. I suggest reading the [README][http://github.com/amro/gibbon] a bit more as I think it'll help clear things up a bit. But to answer your specific question, that API requires you to POST to MailChimp's API:

`POST /campaigns/{campaign_id}/actions/send`

so you should actually be doing something like `gb.campaigns(campaign_id).actions.send.create` since `create` maps onto HTTP POST. That should work.

**Comment by q3-tech** [comment]
Yes, I tried that as well.
But the 'actions.send' is getting confused with ruby's native send method which expects an argument.

Apologies if I'm not clear, English is not my first language.

**Comment by amro** [comment]
Ah, no, then that's a real bug. Let me look into it.

**Comment by amro** [comment]
@q3-tech Thanks for the bug report. Also, your English is great! It was simply a matter of not having enough information. Anyway, I've fixed the bug and pushed version 2.1.3. Please give that a try.
