### ISSUE TITLE
Failing to upsert campaign content

### ISSUE THREAD

**Issue by cantlin** [amro/gibbon#168]
This is probably some kind of stupid mistake on my part, but I'm reporting it here in case it's a real issue.

I can happily create campaigns:

````ruby
gibbon = Gibbon::Request.new
response = gibbon.campaigns.create(self.to_mailchimp_schema)
self.mailchimp_campaign_id = response['id']
````

And update their settings:

````ruby
gibbon.campaigns(self.mailchimp_campaign_id).update(self.to_mailchimp_schema)
````

Unfortunately, I can't seem to update their content. This code doesn't error, but also fails to update the campaign content:

````ruby
begin
  gibbon.campaigns(self.mailchimp_campaign_id).content.upsert(body: { html: "<p>A test</p>" })
rescue Gibbon::MailChimpError => e
  puts "Houston, we have a problem: #{e.message} - #{e.raw_body}"
end
````

The corresponding ``curl`` command works correctly:

````bash
curl --request PUT --url https://us10.api.mailchimp.com/3.0/campaigns/<id>/content \
--user 'anystring:<key>' --header 'content-type: application/json' \
--data '{"html": "<p>A test</p>"}' --include
````

The Gibbon Request object doesn't give me much to examine in success cases. What's the best way of debugging this kind of problem?

**Comment by cantlin** [comment]
I was worried something fishy was going on with my app environment, so I changed the code path to use [curb](https://github.com/taf2/curb):

````ruby
require 'curb'
    gibbon = Gibbon::Request.new

    url = "https://us10.api.mailchimp.com/3.0/campaigns/#{self.mailchimp_campaign_id}/content"
    body = { html: "<p>Test</p>" }

    http = Curl.put url, JSON.dump(body) do |http|
      http.headers['content-type'] = 'application/json'
      http.http_auth_types = :basic
      http.username = 'foo'
      http.password = gibbon.api_key
    end
````

But that works just fine. I'm not sure how to work out what Gibbon is doing differently under the hood.

**Comment by amro** [comment]
Very strange. What do you see when you print the response?

The requests gibbon makes should be identical to those you've created by hand. I'll try it to see if I can reproduce the issue in the morning.

Thanks,
Amro

**Comment by cantlin** [comment]
It's weird - the return value is a ``Gibbon::Request`` object, not a JSON response as normal:

````ruby
gibbon.campaigns(c.mailchimp_campaign_id).content.upsert(body: { html: "<p>Test</p>" })
#<Gibbon::Request:0x00000005d3eb90 @path_parts=["campaigns", "<campaign_id_removed>", "content", "upsert", {:body=>{:html=>"<p>Test</p>"}}, "campaigns", "<campaign_id_removed>", "content", "upsert", {:body=>{:html=>"<p>Test</p>"}}], @api_key="<api_key_removed>", @api_endpoint=nil, @timeout=15>

**Comment by amro** [comment]
Ah ha! Upsert was added in 2.1. Gibbon attempts to conform to semver. I bet you are on 2.0.x. It's safe to upgrade to 2.1.x.

Thanks,
Amro

**Comment by cantlin** [comment]
Ah! Sure enough:

````bash
cantlin@ubuntu:~/src/app$ bundle show | grep gibbon
  * gibbon (2.0.0)
````

I just added ``gem 'gibbon'`` to my Gemfile today - might be worth leaving a note in the README or upping the default Bundler picks.

Many thanks for the quick help :)

**Comment by amro** [comment]
Back at my computer. Yes, I'm sorry you ran into this. There is a note in the README but perhaps it should be more prominent. I'm not sure why Bundler would pick an older version than the latest released if you haven't specified the pessimistic version operator.

That doesn't make sense to me. And actually, 2.2.0 is the latest version so I'd suggest starting with it.

I could release an old 2.0.x release w/ upsert defined and have it throw. But really, I'm trying to conform to semver since that's the general expectation in the community.

If you're curious as to why this happens, Gibbon builds URLs using the builder pattern. Each dot separated call on the request object appends a path segment. And the verbs are essentially terminators that make the request based on the prior path segments. Since upsert was not defined as a terminator in 2.0.x, it was assumed to be a path segment.
