### ISSUE TITLE
Select fields params

### ISSUE THREAD

**Issue by casper91** [amro/gibbon#177]
Maybe I'm doing it wrong but I'm struggling to select specific fields.
I would expect something like this:
```Ruby
lists.retrieve(params: {fields: ['id', 'name']})
```
But this doesn't seem to work.

**Comment by amro** [comment]
So again, I tried with curl, and again produced the same behavior as Gibbon instead of what I would expect to be returned based on the documentation.

What I expected to work with curl:

    curl --request GET --url 'https://us1.api.mailchimp.com/3.0/lists/MYLISTID?fields[0]=FNAME' --user 'anystring:MYAPIKEY' --include

Only I url encoded the brackets so it's actually:

    curl --request GET --url 'https://us1.api.mailchimp.com/3.0/lists/MYLISTID?fields%5B0%5D%3DFNAME' --user 'anystring:MYAPIKEY' --include

The fields don't seem to be included in the response, which is what I expect to be case.

Maybe we misunderstand what "return" means in "a comma-separated list of fields to return"? No extra data is returned when I set fields.

Also confusing is the type is an array but the description says "comma-separated list," which I would take to mean a string. e.g. `fields=FNAME,LNAME` and not `fields[0]=FNAME&fields[1]=LNAME`. Which is it? I suggest asking MC this as well. Sorry to punt again but their API folks will have information better information on how these things work (and maybe they can clarify their documentation a bit too!).

**Comment by casper91** [comment]
I will try ask them about this also. I will return with an answer.

**Comment by amro** [comment]
Thanks for that

**Comment by casper91** [comment]
So their definition of a list is just a comma separated string e.g. "id, name". So if want wanted just the id and names of all list, one should use.
```Ruby
gibbon.lists.retrieve(params: {:"fields"=> "lists.id,lists.name"})
```
I think I will make a PR with these examples, since they are not that trivial to understand from their API :(

**Comment by amro** [comment]
Sigh. Thanks again. This is definitely something good to document in the README.

Did that syntax actually work? That syntax doesn't look right to me. It said an "array" and when I tried "FNAME" I received an error back from the API. I didn't try this dot notated business (is that correct or did you mean to interpolate values in? i.e. did you mean:

    gibbon.lists.retrieve(params: {"fields" => "#{lists.id},#{lists.name}"})  

?

**Comment by amro** [comment]
Thanks for the PR and for asking MC about the API. It's sincerely appreciated.

**Comment by casper91** [comment]
Your welcome, and thanks for the nice job on this gem. Keep it up!
