### ISSUE TITLE
Final welcome email not sent to users after using gibbon gem to add user to list

### ISSUE THREAD

**Issue by jessesanford** [amro/gibbon#196]
Final welcome email checkbox is checked on the list settings page. It seems that gibbon gem signup is somehow incompatible with that setting?

**Comment by amro** [comment]
I need a little more information. How is it incompatible? How does this relate to the API, etc.

**Comment by amro** [comment]
The text below "Send a final welcome email" says "when people opt-in to your list." Are you using single opt-in when you make API calls to subscribe a user? If so, I suspect that's why the welcome email isn't being sent.

This [doc](http://developer.mailchimp.com/documentation/mailchimp/guides/manage-subscribers-with-the-mailchimp-api/) explains you should set the list member's status to "pending" instead of "subscribed" if you want to use double opt-in.

**Comment by jessesanford** [comment]
Yep was using single opt-in. I will try to find a solution to sending welcome email to users using single opt-in and report back. You can close this issue as it is intended behavior.

**Comment by amro** [comment]
👍

**Comment by nuclearspike** [comment]
What was the solution for sending the welcome email?

**Comment by amro** [comment]
Try setting a status of pending instead of subscribed if you want to use double opt-in and send a welcome email

**Comment by nuclearspike** [comment]
Thanks!

**Comment by amagoon** [comment]
So is there no way to send a 'final welcome' email without a double opt-in directly through mailchimp? How did you work around this? I am considering using a transactional email service instead for this like Mandrill or SES.

**Comment by amro** [comment]
I think that's a function of double opt-in but this is really a question for MailChimp support. They'd know more about the specifics of their service.
