### ISSUE TITLE
Video Examples?

### ISSUE THREAD

**Issue by vonromson** [amro/gibbon#201]
can you make a example video for subscribing members to a newsletter, creating campaigns, using template editing (mc:edit), and adding a content using Ruby on Rails? I would gladly appreciate it.

**Comment by amro** [comment]
No, sorry but I don't have time to do that due to other commitments.

That said, Gibbon's README has a bunch of great examples but generally you should look at MailChimp's API documentation and understand how paths and parameters for endpoints map onto Gibbon. It's basically 1-to-1 other than hyphens in URL segments becoming underscores.

Also, MailChimp has a fantastic support team that understands their API. They're the very best folks to reach out with if you want to understand the behavior of specific API endpoints.

**Comment by vonromson** [comment]
body = {
  template: {
    id: template_id,
    sections: {
      "**_name-of-mc-edit-area_**": "Content here"
    }
  }
}

gibbon.campaigns(campaign_id).content.upsert(body: body)


sorry for questions, but i am very new to ruby on rails, and I'm having trouble using the mailchimp's API, what should i input in the bolded text? do you have an example project that i can fork using the fields included in the gibbon's readme? thank you very much.

**Comment by amro** [comment]
It's okay. Getting started is hard. Stick with it! That is the name of the content section you want to edit. I don't know if you can get a list of editable regions easily programmatically. I don't think [you can](http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/content/) but I could be wrong.

All I see in the docs is the ability to fetch the entire HTML contents. So you'd have to load that up into a parser of some sort and look for regions manually if you're trying to automate something. If you just want to update a known region then you can just find the name of the content section yourself. You'll want to double check MailChimp's API docs (linked in the prior sentence) and ask their support team about fetching a list of editable regions programmatically.

P.S. I don't recall whether the attribute is called "mcedit" (or maybe it's "mc-edit" or "mc:edit").
