### ISSUE TITLE
404 when getting members from a list

### ISSUE THREAD

**Issue by NullVoxPopuli** [amro/gibbon#212]
I noticed in the API playground, there is this:

					"targetSchema": "https://us1.api.mailchimp.com/schema/3.0/Lists/Members/Collection.json",

which i suspect is helping cause the error
```
Gibbon::MailChimpError: the server responded with status 404 @title="Resource Not Found", @detail="The resource 'Members_Collection' could not be found.", 
```
This is my request:

`gibbon.lists(id).members.retrieve`

I can successfully get a lists and a singular list, but getting members, or a singular member throws this error:
```
Gibbon::MailChimpError: the server responded with status 404 @title="Resource Not Found", @detail="The resource 'Members_Instance' could not be found."
```

Am I doing something wrong?

**Comment by amro** [comment]
Are you sure your list id is correct? I just tried this and it worked fine. The only other thing I can think of is maybe the API key doesn't have sufficient permissions?

**Comment by NullVoxPopuli** [comment]
`gibbon.lists(id).retrieve` works (returns the list)

here is my api log from mailchimp's web interface
![image](https://cloud.githubusercontent.com/assets/199018/17494170/8c0b0b00-5d81-11e6-9740-de986cba1be4.png)

the successful members calls at the bottom are from the api playground.
the failure up top is when I did 
```ruby
gibbon.lists(id).members.retrieve
```

**Comment by NullVoxPopuli** [comment]
the api key i'm using is on my user (the owner) of my test mailchimp account

**Comment by NullVoxPopuli** [comment]
apparently this works: 

```ruby
list.members(mailchimp_id).retrieve
```

**Comment by NullVoxPopuli** [comment]
the Members_Instance error is when i try to do `list.members(id).update(...)`

**Comment by NullVoxPopuli** [comment]
`list.members(mailchimp_id).upsert(...)` works, but update doesn't :-\ weird

**Comment by amro** [comment]
Let's start with just the first one and try to figure it out. Gibbon is a very simple wrapper around the API. If you call `gibbon.lists(id).members.retrieve`, it will generate a path "lists/{id}/members" -- no where in that path is Members/Collection.

You can see what path gibbon will generate for a request by calling `path` instead of a verb. For instance, try `gibbon.lists(id).members.path`. That path should map directly onto a path from the (API reference)[http://developer.mailchimp.com/documentation/mailchimp/reference/overview/].

Try that for one of your failing calls and see if it generates the path you expect it to based on the reference. If it doesn't, then you're not making the call correctly.

I wouldn't expect `gibbon.list.members(mailchimp_id).retrieve` to work unless you specify a list id as some of the examples in the README do, but maybe MailChimp's API searches all of your lists in that case. I don't know.

**Comment by NullVoxPopuli** [comment]
for clarification, when I've started a code snipped with `list` I mean to imply that I have a (query object?)

it's just the result of `gibbon.lists(id)` with a specific id.

I'll try this out tomorrow morning. thanks!

**Comment by amro** [comment]
Just to be clear: you're not trying to reuse request objects, are you? Those are very light one-time use objects. Gibbon uses the builder pattern -- each call chained onto the request object updates an internal path. When you terminate the call chain with a verb, the request is made.

Thanks,
Amro

**Comment by NullVoxPopuli** [comment]
ah, that's probably why it isn't working. 

I was memoizing each list I was managing. I'll not do that. thanks!

**Comment by amro** [comment]
Awesome. Lmk if you run into any other trouble.

Thanks,
Amro

**Comment by NullVoxPopuli** [comment]
That did the trick! thanks!

**Comment by amro** [comment]
I added a note early on in the README to help others who run into this. Glad it's working for you.

**Comment by jjustinwhite** [comment]
I missed the note! Was also memoizing the request object. Oops! All fixed after removing the memoization on the request.
