### ISSUE TITLE
Support for automations?

### ISSUE THREAD

**Issue by stevenspiel** [amro/gibbon#247]
Mailchimp uses automations, and I particularly would like to [queue an email in an automation](https://developer.mailchimp.com/documentation/mailchimp/reference/automations/emails/queue/)

I would expect this to work:

```rb
Gibbon::Request.new.automations(workflow_id).emails(workflow_email_id).queue(params: { email_address: email_address })
```

But nothing is logged, and no API call is made. The return value is a `Gibbons::Request` object. Do you not support automations?

**Comment by amro** [comment]
I've not tried to use Gibbon for automations but it'll probably just work.
The issue here is you've not provided a verb at the end of your callchain.
Please see the bit of the readme that talks about mapping MC API calls onto
gibbon and how you must end a call with a verb that maps onto an http verb.

I can leave a more detailed response when I get back to my desk.

**Comment by amro** [comment]
The MC doc you linked to states this endpoint expects a POST so you should terminate your call with a call to create(). The email address is expected to be part of the request's body as opposed to being a query parameter so you should use "body" instead of params.

Try something like this:

```ruby
Gibbon::Request.new.automations(workflow_id).emails(workflow_email_id).queue.create(body: { email_address: email_address })
```

**Comment by stevenspiel** [comment]
Beautiful. That did the trick. Thank you!
