### ISSUE TITLE
uninitialized constant Gibbon::Request

### ISSUE THREAD

**Issue by kashiftufail** [amro/gibbon#258]
Hi,

  I install gibbon gem and when this below line execute

      Gibbon::Request.api_key = "API_KEY"

  i have this error "uninitialized constant Gibbon::Request"

   My ruby version is 2.1.3 and Rails on 3.2.11

 This was also not help me  https://stackoverflow.com/questions/38022764/uninitialized-constant-gibbonrequest-nameerror.

 when i install gibbon from here 
          
         gem 'Gibbon' to gem 'gibbon', :git => 'https://github.com/amro/gibbon.git'

 Then bundle install given me below error

        /home/kashif/.rvm/gems/ruby-2.1.3@metgibon/gems/haml-3.1.8/lib/haml/util.rb:348:in `try_sass': uninitialized constant Haml::Util::Sass (NameError)

 Can you please help?

 Thanks

**Comment by amro** [comment]
It sounds like you need to import Gibbon in the file you're trying to use it in.

e.g.

```import gibbon```

**Comment by kashiftufail** [comment]
No I have written 

     require 'gibbon' 
In my controller file but same error.

Thanks

**Comment by amro** [comment]
What version of Gibbon appears in your Gemfile.lock?

**Comment by kashiftufail** [comment]
The version is 
  
            gibbon (3.1.1)

and it is install from here

            remote: https://github.com/amro/gibbon.git

**Comment by amro** [comment]
So looking at your original message (sorry I missed the very last bit) I realized gibbon isn't even *installed* properly. That's why you're getting the error. The question is why bundle install is not working.

But the error you show is not entirely clear. This looks like it was edited somehow:

```  /home/kashif/.rvm/gems/ruby-2.1.3@metgibon/gems/haml-3.1.8/lib/haml/util.rb:348:in `try_sass': uninitialized constant Haml::Util::Sass (NameError)```

Can you paste the full output from bundle install, please?

Ultimately you need to figure out why bundle install is failing. That is the issue.
