### ISSUE TITLE
Retrieving individual emails who opened a campaign 

### ISSUE THREAD

**Issue by kebabbas** [amro/gibbon#261]
What I'm trying to do is to retreive a list of email addresses who open particular emails, so I can see whether they have completed a desired action 

For a campaign with a particular `campaign_id`, there exists integer n such that `gibbon.reports("campaign_id").retrieve.body["_links"][n]["rel"]` = `open-details` and `gibbon.reports("campaign_id").retrieve.body["_links"][n]["href"]` = `"https://us6.api.mailchimp.com/3.0/reports/campaign_id/open-details"` - the last link I assumed to be an API URL I can use in a GET request

Using the gem Rest-Client, and doing the following in an irb environment..

```
emails = RestClient::Request.execute(method: :get, url: url, user: 'user', password: ENV.fetch("MAILCHIMP_TOKEN"))

JSON.parse(emails.body)

```

returns 

`{"members"=>[], "campaign_id"=>"cff38a25bd", "total_opens"=>0, "total_items"=>0, "_links"=>[{"rel"=>"parent", "href"=>"https://us6.api.mailchimp.com/3.0/reports/cff38a25bd/", "method"=>"GET", "targetSchema"=>"https://us6.api.mailchimp.com/schema/3.0/Definitions/Campaigns/Response.json"}, {"rel"=>"self", "href"=>"https://us6.api.mailchimp.com/3.0/reports/cff38a25bd/open-details", "method"=>"GET", "targetSchema"=>"https://us6.api.mailchimp.com/schema/3.0/Definitions/Reports/ClickDetails/CollectionResponse.json"}]}`

Is it the case that either
- This (using this URL in a GET Request) is the right way to pull this list of emails, but there is something related to my execution of it that is wrong
- There is another way to get this list of emails, which I haven''t mentioned here
- This is not possible

**Comment by amro** [comment]
Looking at [MailChimp’s doc](http://developer.mailchimp.com/documentation/mailchimp/reference/reports/open-details/) we see that what you’re trying to do should be possible. I think the URL is correct. You didn’t get an error as a response so I suspect you’er doing it right, but I’m not sure. (Gibbon uses “apikey” for the basic auth username. I don’t know whether MC accepts `user`. That’s one thing to check.)

It’s been a long time since I worked at MailChimp, but it used to be that opens had an approximately 10 minute delay due to the way they were processed. Do note that in your testing.

**Comment by kebabbas** [comment]
Thanks for the help, a little playing around with that link in the documentation and I was fine

Thanks very much!
