### ISSUE TITLE
Support Webhooks

### ISSUE THREAD

**Issue by frizman21** [amro/gibbon#262]
Mailchimp has a pretty useful feature in the [webhooks](https://developer.mailchimp.com/documentation/mailchimp/guides/about-webhooks/). It doesn't appear that gibbon supports this today. This is a request to implement the data structure and related enumerations to make the full featured. My specific use-case is feedback from a critical campaign - it not being successful needs to raise alarms and likely automatically or easily restarted.

**Comment by amro** [comment]
Hi @frizman21. Thanks for the suggestion. Gibbon is a wrapper around MailChimp’s REST API (API 3.0) and it’s Export API. It supports managing web hooks via their API, but processing them is not in the scope of what it does.

In fact, Gibbon is a thin wrapper around the API that maps it onto Ruby syntax so one doesn’t need to deal with constructing URLs, etc directly. Gibbon does not contain any model mappings for MailChimp objects like campaigns, users, lists or special handling for each endpoint. It just constructs a request and returns the parsed JSON payload and it’s up to the consumer to implement the rest. This is partially so the gem can support updates to the API without itself needing to be updated, thereby decreasing the amount of maintenance I need to do and the time one needs to wait to use Gibbon after an API change or addition.

Because of this, I won’t implement this request.
