### ISSUE TITLE
the server responded with status 400 @title="Invalid Resource"

### ISSUE THREAD

**Issue by thibaultlanery** [amro/gibbon#265]
Hello, 

I have succeded in composing member list through a landing page with a name and email form that create a user both in my app and mailchimp.
 Nevertheless I have one error message on a email I tested randomly.
alex@gmail.com
To limit any email mistakes, I have added a regex in my User model on create. But this seems not sufficient and seems to be proper to gibbon email validation.

here is the error message:

@detail="alex@gmail.com looks fake or invalid, please enter a real email address.", @body={"type"=>"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/", "title"=>"Invalid Resource", "status"=>400, "detail"=>"alex@gmail.com looks fake or invalid, please enter a real email address.", 

Here is my service code:

`class SubscribeToNewsletterService
  def initialize(user)
    @user = user
    @gibbon = Gibbon::Request.new(api_key: ENV['MAILCHIMP_API_KEY'])
    @list_id = ENV['MAILCHIMP_LIST_ID']
  end

  def call
    if @user.email
    @gibbon.lists(@list_id).members.create(
      body: {
        email_address: @user.email,
        status: "subscribed",
        merge_fields: {
        FNAME: @user.name,
        #   LNAME: @user.last_name
        }
      }
    )
    end
  end
end`

User model:

after_create :subscribe_to_newsletter

validates :email, presence: true, uniqueness: true
validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
validates :name, presence: true

  def subscribe_to_newsletter
    SubscribeToNewsletterService.new(self).call
  end

Is there any gibbon method or best practise I could use to check validity of infos submitted from my users to prevent error message of the API? 

Thanks in advance for your help!

Thibault

**Comment by amro** [comment]
Gibbon wraps the API and nothing more so the errors you’re receiving are due to MailChimp’s validation. I have never heard of this particular error though. I recommend reaching out to MailChimp’s API support team to ask how they validate email authenticity.

As far as best practices, you should handle API errors, in general. For instance, attempting to subscribe a user that is already added to a given list results in an error. You can handle the error or you can use `upsert` instead. There’s an example of doing so in Gibbon’s ReadMe. I wouldn’t recommend a complex regex for validating email. I would go with something rudimentary (e.g. does the string contain an @ and is it long enough) and let MailChimp do the full validation.

I’m happy to attempt to answer Gibbon specific questions.

**Comment by thibaultlanery** [comment]
Thank you for your time and help

Thibault
