### ISSUE TITLE
How to delete a member from a list?

### ISSUE THREAD

**Issue by gregblass** [amro/gibbon#300]
Hey there!

I'm not sure if this changed recently in the MailChimp API, but sending a delete request when removing a subscriber from a list seems to just archived them: https://mailchimp.com/developer/reference/lists/list-members/

The last tab there says 'actions' - 'delete permanent' - however I'm having trouble mapping that to a gibbon request:

`POST /lists/{list_id}/members/{subscriber_hash}/actions/delete-permanent`

How would that look?

**Comment by amro** [comment]
Try something like

gibbon.lists(list_id).members(member_id).actions.delete_permanent.create()


This is a bit of a weird api semantically because they’ve used HTTP POST instead of DELETE.

**Comment by gregblass** [comment]
It ended up being .actions(‘delete-permanent’).create

Replying from my phone but you can close this!

**Comment by amro** [comment]
Gotcha. Does .actions.delete_permanent.create() work?

**Comment by ahaverty** [comment]
@amro @gregblass 
I can confirm that `.actions.delete_permanent.create`
permanently deletes. Glad this issue was here, that would have taken me awhile considering Mailchimp's api doc's still say to just send a DELETE 🤷 
![image](https://user-images.githubusercontent.com/2920947/85702945-cd30b780-b6d6-11ea-912e-bad9c1c23afd.png)

**Comment by amro** [comment]
Thanks for confirming!
