### ISSUE TITLE
How to unsubscribe email that is bounced, pending, or archived?

### ISSUE THREAD

**Issue by mintii** [amro/gibbon#320]
`Gibbon::MailChimpError: the server responded with status 405 @title=“Method Not Allowed”, @detail=“This list member cannot be removed. Can not archive a contact that is bounced, pending or archived”"`

Hello I get the error above with a email address that I'm deleting. 
I'm using the following line: 
`gibbon.lists(list_id).members(user_email_hashed).delete` 

The recommendations I read online suggest to use Mailchimp API's `delete-permanent` option. 
`POST /lists/{list_id}/members/{subscriber_hash}/actions/delete-permanent`

I was wondering what suggestions you have on how to use this method but with the Gibbon gem? Thanks in advance! :)

**Comment by amro** [comment]
Hi @mintii. Gibbon is a very simple wrapper around the Mailchimp API without any special logic of its own. That means one can map the path for one of Mailchimp's API endpoints to Gibbon mostly 1:1.

I've not tried this particular API, but it should be something like:

```gibbon.lists(list_id).members(user_email_hashed).actions.delete_permanent.create```

There's a bit more about how to map endpoint paths to Gibbon's syntax in the [documentation](https://github.com/amro/gibbon/blob/master/README.markdown), which is admittedly light weight given the nature of the library. In this case, `create` is called at the end because you point out the API expects one to use the HTTP `POST` verb.

Does that help?

**Comment by mintii** [comment]
Thank you this is helpful guidance! I'll look into how I can implement this for my project.

**Comment by mintii** [comment]
If someone comes across this issue, I ended up doing a no-op when matching the status code received from MailChimp. 
`Gibbon::MailChimpError.status_code == 405`

It turns out `delete_permanent` is a bit too permanent. My test account is now _forever_ unable to subscribe to the app's Mailchimp's lists. 😅
